services:
  spark:
    image: docker.io/bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
    - airflow-kafka
    ports:
      - '8088:8080'
      - '7077:7077'
    volumes:
      - '.:/test-files:rw'
  spark-worker:
    image: docker.io/bitnami/spark:3.5.0
    depends_on:
      - spark
    networks:
    - airflow-kafka
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-1:
    depends_on:
        - spark
        - spark-worker
    image: docker.io/bitnami/spark:3.5.0
    networks:
    - airflow-kafka
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    

  jupyterlab:
    image: jupyter/pyspark-notebook:latest
    depends_on:
      - spark
    environment:
      - SPARK_MASTER=spark://spark:7077
    networks:
    - airflow-kafka
    ports:
      - '8888:8888'
      - '9094'
      - '9092'
    volumes:
      - './notebooks:/home/jovyan/work:rw'
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

networks:
  airflow-kafka:
    external: true
