arriba:
	docker-compose -f kafka-tools.yml up -d

downall:  
	docker-compose down -f kafka-tools.yml --rmi all

pg_go:
	docker-compose -f PG/pg.yml up -d

pg_down:
	docker-compose -f PG/pg.yml down

pg_down_all:
	docker-compose -f PG/pg.yml down --rmi all